### ISSUE TITLE
bulej93 - bidState is update before loan is repaid

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#116]
bulej93

high

# bidState is update before loan is repaid

## Summary
the bid state is updated before the loan is repaid
## Vulnerability Detail
when repaying the loan, if the payment amount is greater than the owed amount, then the bid.state is set is PAID. this comes before the actual funds are sent from the borrower to the lender. on top of that the collateral is also sent back to the borrower before the lender receives his principal back.
## Impact
the borrower can enter a large amount as payment, have the bid state set to paid, get his collateral back without having to payback the amount borrowed
## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L727-L751
## Tool used

Manual Review

**Comment by bulej93** [comment]
Escalate for 10 USDC

**Comment by Trumpero** [comment]
This issue is clearly invalid. After updating bid.state to PAID, the payment funds will be pulled from the borrower, ensuring the repayment of the loan proceeds as normal.
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L747-L751

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
