### ISSUE TITLE
bulej93 - Borrowers can get loans from markets were the are not trusted market forwarders

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#118]
bulej93

medium

# Borrowers can get loans from markets were the are not trusted market forwarders

## Summary
trusted market forwarder can be bypassed by borrowers
## Vulnerability Detail
for a borrower to get a loan from a certain market they have to be a trusted market forwarder of that market. this check happens when they submit their bids for getting a loan. however this check can be bypassed when a lender creates a commitment and adds borrowers to the list of trust borrowers. this doesn't check whether the borrowers are trusted to be in that market.
## Impact
borrowers can get loans from any market of their choosing 
## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L300-L400
## Tool used

Manual Review

**Comment by bulej93** [comment]
Escalate for 10 USDC.

since lenders are able to create commitments and add borrowers without having to check whether the borrowers are trusted forwarders of that market, this presents an opening for borrowers to bypass the check on where they are authorized to borrow from.
as long as they are added by a lender in that commitment that can borrow from that market whether they are trusted or not.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
As pointed out by the Lead judge `marketForwarder` is checked whether it is trusted.
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2Context.sol#L32-L45
