### ISSUE TITLE
chaduke - _withdrawCollateral() withdraws the wrong amount of ERC 20 tokens.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#140]
chaduke

medium

# _withdrawCollateral() withdraws the wrong amount of ERC 20 tokens.

## Summary
_withdrawCollateral() withdraws the wrong amount of ERC 20 tokens.  The main problem is that while the input argument for _withdrawCollateral() is ``_amount``, the function uses the `` _collateral._amount`` to withdraw all the balance of ERC20 tokens from the contract of ``CollateralEscrowV1``.

## Vulnerability Detail
To see why _withdrawCollateral() withdraws the wrong amount of ERC 20 tokens, let's see the flow of ``CollateralEscrowV1#withdraw()->withdrawCollateral()``:

1. Let's assume the collateral type to be withdrawn is ERC20, that is ``_collateralType == CollateralType.ERC20``.

2. ``CollateralEscrowV1#withdraw()``will decease the balance by the input ``_amount``:
[https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L101](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L101)

3. However, when it calls ``withdrawCollateral()``, the amount that will be transferred is  ``collateral._amount``, which is not necesarily equal to ``_amount``.
[https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L165-L170](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L165-L170)

4. Note that when the collateral is ERC1155, the ``_amount`` is used instead:
```javascript
 else if (_collateral._collateralType == CollateralType.ERC1155) {
            bytes memory data;

            IERC1155Upgradeable(_collateralAddress).safeTransferFrom(
                address(this),
                _recipient,
                _collateral._tokenId,
                _amount,
                data
            );
        } else {
```

This confirms that for ERC20 collateral, ``_amount`` should be used as well, not ``_collateral._amount``!

## Impact
When the input ``_amount <  _collateral._amount``, for ERC collateral, more tokens will be withdrawn by ``withdrawCollateral()`` than it is supposed to be. 

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
Use  ``_amount`` instead of ``_collateral._amount`` for withdrawing ERC20 collateral
```diff
function _withdrawCollateral(
        Collateral memory _collateral,
        address _collateralAddress,
        uint256 _amount,
        address _recipient
    ) internal {
        // Withdraw ERC20
        if (_collateral._collateralType == CollateralType.ERC20) {
            IERC20Upgradeable(_collateralAddress).transfer(
                _recipient,
-                _collateral._amount
+             _amount
            );
        }
        // Withdraw ERC721
        else if (_collateral._collateralType == CollateralType.ERC721) {
            require(_amount == 1, "Incorrect withdrawal amount");
            IERC721Upgradeable(_collateralAddress).transferFrom(
                address(this),
                _recipient,
                _collateral._tokenId
            );
        }
        // Withdraw ERC1155
        else if (_collateral._collateralType == CollateralType.ERC1155) {
            bytes memory data;

            IERC1155Upgradeable(_collateralAddress).safeTransferFrom(
                address(this),
                _recipient,
                _collateral._tokenId,
                _amount,
                data
            );
        } else {
            revert("Invalid collateral type");
        }
    }
```

**Comment by cducrest** [comment]
Escalate for 10 USDC

This is invalid.
The issue points to the fact that the input parameter of `CollateralEscrowV1.withdraw()` is not used to withdraw ERC20 tokens and `_collateral._amount` is used instead. This is not a problem as the values are the same (and cannot be a problem in any way since the whole amount of tokens is withdrawn in all cases).

The value of `_collateral._amount` is set in `CollateralEscrowV1.depositAsset()`:

```solidity
    function depositAsset(
        CollateralType _collateralType,
        address _collateralAddress,
        uint256 _amount,
        uint256 _tokenId
    ) external payable virtual onlyOwner {
        ...
        Collateral storage collateral = collateralBalances[_collateralAddress];
        ...

        collateral._collateralType = _collateralType;
        collateral._amount = _amount;
        collateral._tokenId = _tokenId;
        emit CollateralDeposited(_collateralAddress, _amount);
    }
```

This function is called by `CollateralManager._deposit()` with the value `collateralInfo._amount`, meaning `collateral._amount` in `CollateralEscrowV1` is equal to `collateralInfo._amount` in `CollateralManager`:

```solidity
    function _deposit(uint256 _bidId, Collateral memory collateralInfo)
        internal
        virtual
    {
        ...
        if (collateralInfo._collateralType == CollateralType.ERC20) {
            ...
            collateralEscrow.depositAsset(
                CollateralType.ERC20,
                collateralInfo._collateralAddress,
                collateralInfo._amount,
                0
            );
```

The function `CollateralManager._withdraw()` re-uses the same value `collateralInfo._amount` when withdrawing from the escrow:

```solidity
    function _withdraw(uint256 _bidId, address _receiver) internal virtual {
        for (
            uint256 i;
            i < _bidCollaterals[_bidId].collateralAddresses.length();
            i++
        ) {
            // Get collateral info
            Collateral storage collateralInfo = _bidCollaterals[_bidId]
                .collateralInfo[
                    _bidCollaterals[_bidId].collateralAddresses.at(i)
                ];
            // Withdraw collateral from escrow and send it to bid lender
            ICollateralEscrowV1(_escrows[_bidId]).withdraw(
                collateralInfo._collateralAddress,
                collateralInfo._amount,
                _receiver
            );
            ...
        }
    }
```

As explained in the issue, the `CollateralEscrowV1` will ignore this input value and use `_collateral._amount` instead. To sum up, the escrow ignores `CollateralManager.collateralInfo._amount` and uses `CollateralEscrowV1._collateral._amount`. But the two values are equal as proven here.

This is not a vulnerability and just a result of duplicate information in the two contracts and passing redundant information.

https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/escrow/CollateralEscrowV1.sol#L51-L76

https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L316-L341

https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L393-L419

**Comment by ethereumdegen** [comment]
Github PR: [Fixes amount to withdraw in collateral escrow contract](https://github.com/teller-protocol/teller-protocol-v2/pull/86)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid informational
As pointed out in the escalation there is no issue here as both the values are same and this is an informational issue.
