### ISSUE TITLE
HexHackers - If borrower gets blacklisted by an asset contract their collateral can be permanently frozen

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#149]
HexHackers

medium

# If borrower gets blacklisted by an asset contract their collateral can be permanently frozen

## Summary
Certain tokens like USDC and USDT have the ability to blacklist addresses. If a borrower gets blacklisted by the asset contract their collateral can be permanently frozen. 
## Vulnerability Detail
The functionality of sending collateral back to the borrower is implemented in the _repayLoan() function in the TellerV2 contract:
```solidity
function _repayLoan(/*parameters*/) internal virtual {
//not related functionality

            // If loan is is being liquidated and backed by collateral, withdraw and send to borrower
            if (_shouldWithdrawCollateral) {
                collateralManager.withdraw(_bidId);
            }

//not related functionality
}
``` 
It's impossible for a borrower to transfer their otherwise withdrawable funds to another address. 

If for some reason the borrower got blacklisted by the collateral token contract, these funds will be permanently frozen as now there is no way to move them to another address or specify the recipient for the transfer. 

Here is an example of almost exactly the same issue from a previous Sherlock contest:
https://github.com/sherlock-audit/2023-01-ajna-judging/issues/75
## Impact
Borrower loses funds that should be withdrawable otherwise. However, the probability of a borrower getting blacklisted is low, so setting the severity as Medium. 
## Code Snippet
https://github.com/teller-protocol/teller-protocol-v2/blob/cb66c9e348cdf1fd6d9b0416a49d663f5b6a693c/packages/contracts/contracts/TellerV2.sol#L734
## Tool used
Manual Review

## Recommendation
Consider implementing functionality that lets the borrower change what address receives the collateral.

**Comment by cducrest** [comment]
Escalate for 10 USDC

Issue is not duplicate of https://github.com/sherlock-audit/2023-03-teller-judging/issues/227 and is low/info. 

It does not properly identify the problem being that in the case multiple tokens are used as collateral, all of them will be frozen and not only the blacklisting one. It also does not state that loan cannot be fully repaid because attempting to transfer the collateral back to the borrower will revert. As such, it identifies only a loss of the blacklisted collateral of the borrower, which to me is intended behaviour.

I refer to [this issue](https://github.com/sherlock-audit/2023-02-hats-judging/issues/41#issuecomment-1494727841) where two reports for the same underlying vulnerability have been de-duplicated and changed severity due to not correctly identifying the attack vector.

**Comment by asendz** [comment]
> Escalate for 10 USDC
> 
> Issue is not duplicate of #227 and is low/info.
> 
> It does not properly identify the problem being that in the case multiple tokens are used as collateral, all of them will be frozen and not only the blacklisting one. It also does not state that loan cannot be fully repaid because attempting to transfer the collateral back to the borrower will revert. As such, it identifies only a loss of the blacklisted collateral of the borrower, which to me is intended behaviour.
> 
> I refer to [this issue](https://github.com/sherlock-audit/2023-02-hats-judging/issues/41#issuecomment-1494727841) where two reports for the same underlying vulnerability have been de-duplicated and changed severity due to not correctly identifying the attack vector.

So you basically put some stuff together on top of the underlying issue

- Which is a user getting blacklisted by the asset contract and suffering losses because of it

 and you're calling that a different "attack vector"? What attack vector bro? This is not an attack

You're clearly talking about the same issue. Throwing some words around it doesn't make it a unique issue

Also, I have no idea what your referenced issue has to do with this one but your whole statement is pretty confused either way

**Comment by Love4codes** [comment]
> 

bro this issues are basically the same.

i advice you save 10 USDC

**Comment by cducrest** [comment]
I intend to point out to the fact that the vulnerability identified by this issue is of different severity as the one identified in https://github.com/sherlock-audit/2023-03-teller-judging/issues/227. This issue states the borrower will lose its blacklisted token collateral (which I think is intended behaviour) while https://github.com/sherlock-audit/2023-03-teller-judging/issues/227 points to the fact that the borrower will lose all token collateral when only part of it is blacklisted (i.e. in the case of multiple token collateral).

I think this issue is low/info as it points to an expected behaviour (losing blacklisted collateral) while https://github.com/sherlock-audit/2023-03-teller-judging/issues/227 is medium as it explains a loss of non-blacklisted funds of the borrower.

I refer to a judging decision where the same core vulnerability explained from a different perspective and understood differently has led to issues being de-duped and downgraded.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a duplicate of #227 
Although the impact of both issues are considered low severity based on Sherlock rules, I agree with the points raised by cducrest that these two issues are separate. 
Issue #227 clearly identifies that there are multiple collaterals being deposited, and the user can lose others while being blacklisted only. As mentioned above this would still be considered a user error, but the thinking and approach to identifying such issues (227) is appreciated.
