### ISSUE TITLE
cducrest-brainbot - Owner of TellerV2 can escalate privilege to affect loans statuses using reputationManager

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#151]
cducrest-brainbot

medium

# Owner of TellerV2 can escalate privilege to affect loans statuses using reputationManager

## Summary

The owner of `TellerV2` can set the address for `reputationManager` via `setReputationManager()`. By controlling this address, they can selectively allow repayment of loans as they please. They can decide that some loan will not be able to be repaid and will forcefully default. They can prevent liquidation of certain loans.

## Vulnerability Detail

The function `setReputationManager` can be called by the owner at any time. From this we can assume the contract `reputationManager` can do whatever the owner wants.

```solidity
    function setReputationManager(address _reputationManager) public onlyOwner {
        reputationManager = IReputationManager(_reputationManager);
    }
```

This function is called in [the internal function to repay loans](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L721):
```solidity
    function _repayLoan(
        uint256 _bidId,
        Payment memory _payment,
        uint256 _owedAmount,
        bool _shouldWithdrawCollateral
    ) internal virtual {
        Bid storage bid = bids[_bidId];
        uint256 paymentAmount = _payment.principal + _payment.interest;

        RepMark mark = reputationManager.updateAccountReputation(
            bid.borrower,
            _bidId
        );
```

The owner can decide, based on the `bidId` or the `tx.origin` value to revert or not inside `reputationManager.updateAccountReputation()`, selecting which loan can be repaid or who can repay them.

The `_repayLoan()` is called on every loan repay and [liquidation](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L690)

## Impact

The details for the contest state:

> The owner of the TellerV2 contract(s) is not able to directly withdraw collateral (assuming no contract upgrade) nor are they able to affect loan statuses or committed capital (assuming no contract upgrade).

Owner of TellerV2 can prevent repayment of loans until they are defaulted. They can prevent all liquidators to liquidate a loan apart from themselves to be able to buy out the user collateral.

The owner can analyze the market and notice advantageous loans that have a low debt value to collateral value ratio and prevent repayment of such loans to make them default. They can then buy out the collateral for these loans. (this will always occur as loan debt decrease over time, while collateral value remains constant)

## Tool used

Manual Review

## Recommendation

I cannot tell if it is necessary for the owner to be able to change the address of `reputationManager`. The reputation manager is out of scope for this audit, but I believe it not to be necessary.

If it is necessary, you can introduce a latency in the change: e.g. the owner can propose a new `reputationManager` address and can make the change effective only a week later, after the time it takes for borrower / lender to see it is not evil and respond if it is evil.

**Comment by cducrest** [comment]
Escalate for 10 USDC

Comment from protocol acknowledge this as a valid issue, it seems to be closed because owner/admin is trusted but contest details states:

> Even the Admins/owners should not be able to steal funds from the protocol (assuming no changes to solidity code of course).
...
Market owners should NOT be able to race-condition attack borrowers or lenders by changing market settings while bids are being submitted or accepted (while tx are in mempool). Care has been taken to ensure that this is not possible (similar in theory to sandwich attacking but worse as if possible it could cause unexpected and non-consentual interest rate on a loan) and further-auditing of this is welcome.
...
NOTE: The owner of the TellerV2 contract(s) is not able to directly withdraw collateral (assuming no contract upgrade) nor are they able to affect loan statuses or committed capital (assuming no contract upgrade). One ultimate goal when contract logic can be proven to be sound is to revoke ownership of contracts and make them non-upgradeable after that point. 

Also issues where protocol owner can abuse user the system to affect use loans have been treated as valid: https://github.com/sherlock-audit/2023-03-teller-judging/issues/339, and https://github.com/sherlock-audit/2023-03-teller-judging/issues/497.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
There are no specific restrictions on the teller protocol owner in the readme. 
Hence in cases like these Sponsor knows best the trust assumptions of these roles.
