### ISSUE TITLE
innertia - Collaterals can be stacked in the contract, so if the loan defaults, the lender loses everything.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#189]
innertia

high

# Collaterals can be stacked in the contract, so if the loan defaults, the lender loses everything.

## Summary
When withdrawing collateral, the registered items are withdrawn in order. However, this list can register any collateral at any time.
In other words, after the loan is approved, the borrower or a malicious third party can stack the collateral into the contract forever by registering fraudulent collateral that, for example, refuses to transfer.
This leaves the lender with no guarantee and loses everything.
## Vulnerability Detail
When collateral is withdrawn, CollateralManager's` _withdraw(uint256 _bidId, address _receiver)` is called internally.
This loops through the addresses registered in `_bidCollaterals[_bidId]` and withdraws the collateral.
However, collateral can be added by anyone at any time via `commitCollateral(uint256 _bidId, Collateral[] calldata _collateralInfo)`. (The balance must be at the borrower's address)
If an incorrect collateral is registered in the array after the loan has been approved (e.g., one that refuses to transfer), the loop will fail and all collateral will be permanently unavailable for withdrawal.
Thus, the lender will not be able to obtain any guarantees.
In a low-gas-cost chain, it is possible to register a huge number of collateral so that the block gas limit is exceeded and the function cannot be called, but it is easier to register invalid collateral
## Impact
Collateral gets stuck in the contract and the lender gets no compensation.
## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L394-L409
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/CollateralManager.sol#L117
## Tool used

Manual Review

## Recommendation
Impose collateral access controls. Additionally, limit the amount of time collateral can be added.

Duplicate of #168

**Comment by innertiaJP** [comment]
Escalate for 10 USDC

I believe the essence of this problem is that collateral can be added by anyone at any time via `commitCollateral(uint256 _bidId, Collateral[] calldata _collateralInfo)`.
This is considered in the _Vulnerability Detail_.
>  collateral can be added by anyone at any time via commitCollateral(uint256 _bidId, Collateral[] calldata _collateralInfo). 

**For this reason, I have combined attack vectors derived from the same issue into a single report**. 
Looking at the results of the contest, I see that the sections I mentioned in the _Vulnerability Detail_ are categorized into four issues.

One is the ability to manipulate collateral against an active loan, as already marked as a duplicate.
https://github.com/sherlock-audit/2023-03-teller-judging/issues/168

The second is to register a number of collateral that exceeds the gas limit, thereby preventing the collateral from being withdrawn, which is a duplicate of the following.
https://github.com/sherlock-audit/2023-03-teller-judging/issues/357
As evidence, the following  is written in the _Vulnerability Detail_.
> it is possible to register a huge number of collateral so that the block gas limit is exceeded and the function cannot be called

Third, if one of the arrays contains collateral that refuses to be withdrawn, the entire collateral cannot be withdrawn.
This overlaps with this issue.
https://github.com/sherlock-audit/2023-03-teller-judging/issues/227
The reference in the _Vulnerability Detail_ is as follows.
> (e.g., one that refuses to transfer), the loop will fail and all collateral will be permanently unavailable for withdrawal.

Fourth, this function can be called by anyone.
This is duplicated below.
https://github.com/sherlock-audit/2023-03-teller-judging/issues/169
The description in the _Vulnerability Detail_ is as follows.
> However, collateral can be added by anyone


**These attack vectors I mentioned in this report above were classified into four categories and treated as separate issues.
If that is the case, I would like this issue of mine to be separated and classified as four separate issues.**

**Comment by cducrest** [comment]
I mainly agree with the comment.

I believe all the issues related to the lack of access control of `commitCollateral()` should be treated as duplicate. Many issues just abuse this vulnerability in different ways.

If we keep on considering all the issues revolving around the exact same core problem (here lack of access control) as different, auditors will be incentivized to think about as many ways as possible to exploit the same flaw. Auditors will waste time they could have spent finding more critical bugs for the protocol. This also makes the judging task harder in my opinion.

I personally reported multiple attack vectors of `commitCollateral()` in different issues because I did not know whether they would be judged as duplicate but truly believe they should be.

I don't believe https://github.com/sherlock-audit/2023-03-teller-judging/issues/227 revolves on the lack of access control on `commitCollateral()` as the issue is described without `commitCollateral()` being called by evildoers / third parties.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #168 
Respectfully disagree with the comments here. 
Some of these issues are different and others valid low. Relevant comments have been added to them. 
#169 is about access control, anyone could call commitCollateral and cause a loss of funds. 
#168 - is not about access control, it can happen even when the caller is legitimate.
#357 - can happen even in a legitimate case, although unlikely but a valid medium in addition to malicious use case which could overlap with 169. 

While I understand the debate for considering them together as both these arguments are valid on their own, I think these issues should be separate for the above reasons. Although these purely depend on the code implementation, we will try to include such situations in the guidelines and add some clarity on it.  
Maintaining this issue a duplicate of #168 as there is no new attack vector, only overlapping issues.
