### ISSUE TITLE
T1MOH - Lender force Loan become default

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#202]
T1MOH

high

# Lender force Loan become default

## Summary
in `_repayLoan()` directly transfer the debt token to Lender, but did not consider that Lender can not accept the token (in contract blacklist), resulting in `_repayLoan()` always revert, and finally the Loan will be default.

## Vulnerability Detail
The only way for the borrower to get the collateral token back is to repay the amount owed via _repayLoan(). Currently in the _repayLoan() method transfers the principal token directly to the Lender.
This has a problem:
if the Lender is blacklisted by the principal token now, the debtToken.transferFrom() method will fail and the _repayLoan() method will always fail and finally the Loan will default.

See also https://github.com/sherlock-audit/2023-01-cooler-judging/issues/23
## Impact
Lender forced Loan become default for get collateral, borrower lost collateral

## Code Snippet
https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/TellerV2.sol#L747

## Tool used

Manual Review

## Recommendation
Instead of transferring the debt token directly, put the debt token into the protocol and set like: withdrawBalance[token][lender] += amount, and provide the method withdraw(address token, address receiver) for lender to get principal token back

**Comment by pauliax** [comment]
Escalate for 10 USDC.
This is more of a Medium type of issue, not a High because getting blacklisted by USDC is a hypothetical scenario and is not very common.

**Comment by cducrest** [comment]
I disagree with the escalation.

The issue does not require the lender to become blacklisted as they can transfer the loans using the `LenderManager` to a blacklisted address. This means the attack is possible even when the lender does not become blacklisted as long as one blacklisted address exists (certain for USDC, very likely for any blacklisting token).

This is explained in https://github.com/sherlock-audit/2023-03-teller-judging/issues/393, https://github.com/sherlock-audit/2023-03-teller-judging/issues/468, and https://github.com/sherlock-audit/2023-03-teller-judging/issues/212.

Based on the result of the judging in https://github.com/sherlock-audit/2023-02-hats-judging/issues/41#issuecomment-1494727841, it could be that this issue is marked as low/info and de-duplicated from 393, 468, and 212 which should remain duplicate valid high.

**Comment by iamjakethehuman** [comment]
Disagree with @cducrest comment.
In order for the vulnerability to take place, a token using a blacklist should be used. The majority of tokens do not implement a blacklist logic. Considering this an external factor. I believe it should be a valid M.

**Comment by T1MOH593** [comment]
Using USDC as external factor in this case is similar to attracting malicious user to hack in High as external factor. If take into consideration market cap and prevalence of USDC. So using USDC can't be counted as external factor.

**Comment by iamjakethehuman** [comment]
A vulnerability appearing only when certain/ unusual tokens are used, when any tokens are expected, has historically been considered a Medium severity vulnerability.
That’s all I have to say. I Will leave to the judge to decide

**Comment by T1MOH593** [comment]
Want to refer this issue https://github.com/sherlock-audit/2023-01-cooler-judging/issues/23

**Comment by ethereumdegen** [comment]
Github PR: [Issue 225 - Separate logic for repay and collateral withdraw](https://github.com/teller-protocol/teller-protocol-v2/pull/69)

**Comment by hrishibhat** [comment]
Escalation accepted

Valid high
The impact of this issue is a valid high. Although the other issues are better with an additional point it can be transferred to a blacklisted address, there is no complex attack vector here that needs to separate these issues. I think these can be considered duplicates together. 
Making #212 the primary issue.
