### ISSUE TITLE
J4de - As long as one token withdraw fails, the entire collateral may fail to withdraw

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#21]
J4de

high

# As long as one token withdraw fails, the entire collateral may fail to withdraw

## Summary

As long as one token withdraw fails, the entire collateral may fail to withdraw

## Vulnerability Detail

```solidity
File: CollateralManager.sol
400     function _withdraw(uint256 _bidId, address _receiver) internal virtual {
401         for (
402             uint256 i;
403             i < _bidCollaterals[_bidId].collateralAddresses.length();
404             i++
405         ) {
406             // Get collateral info
407             Collateral storage collateralInfo = _bidCollaterals[_bidId]
408                 .collateralInfo[
409                     _bidCollaterals[_bidId].collateralAddresses.at(i)
410                 ];
411             // Withdraw collateral from escrow and send it to bid lender
412             ICollateralEscrowV1(_escrows[_bidId]).withdraw(
413                 collateralInfo._collateralAddress,
414                 collateralInfo._amount,
415                 _receiver
416             );
417             emit CollateralWithdrawn(
418                 _bidId,
419                 collateralInfo._collateralType,
420                 collateralInfo._collateralAddress,
421                 collateralInfo._amount,
422                 collateralInfo._tokenId,
423                 _receiver
424             );
425         }
426     }
```

The borrower will call the `CollateralManager#withdraw` function when withdrawing the collateral, and further call the `_withdraw` function, which will try to transfer all tokens. The problem is that as long as there is a token transfer failure, the entire collateral will become unavailable.

There are several situations that cause a certain token transfer to fail (there may be more):

1. There is a problem with the token contract itself
2. Malicious lenders require borrowers to provide collateral for a malicious token
3. Any attacker injects a malicious token through `commitCollateral`
4. The borrower's receiving address is band by a certain token

All tokens are external dependencies, and all funds cannot be lost because of an external dependency.

## Impact

The borrower may have repaid all the loans in batches, but failed to withdraw the collateral, resulting in a loss of funds.

## Code Snippet

https://github.com/teller-protocol/teller-protocol-v2/blob/cb66c9e348cdf1fd6d9b0416a49d663f5b6a693c/packages/contracts/contracts/CollateralManager.sol#L400-L426

## Tool used

Manual Review

## Recommendation

It is suggested that the borrower can actively retry the withdrawal of the specified token.

Duplicate of #169

**Comment by yttriumzz** [comment]
Escalate for 10 USDC

Teller Protocol is support any ERC20 token.

A attacker may offer a seemingly normal and very favorable loan:
 - Lend: worth 1000 USD
 - Collateral 1: WETH worth 1000 USD
 - Collateral 2: TokenA worth 10 USD

TokenA is controlled by the attacker. For the borrower, there is no need to consider whether TokenA is malicious, and only need to spend 10USD to purchase TokenA to obtain the loan. And the borrower believes that as long as the transaction is completed, whether TokenA does evil will not affect him.

Everything is normal until the lender pays off the loan and will withdraw the collateral. The attacker targeted to prevent TokenA from transferring money to the borrower. **Since the Teller Protocol only supports one-time withdraw all collaterals**, the transfer of TokenA revert and the WETH collaterals were also locked.

Now, whether WETH worth 1000USD can be withdrawn depends entirely on the attacker, and the attacker can even use this to blackmail the borrower.

**Comment by Trumpero** [comment]
I disagree with the escalation. The situation where the borrower accepts malicious collateral from the lender should be considered as a user mistake (low/info). The only valid medium scenario in this issue is if someone calls commitCollateral on behalf of the borrower. Therefore, I believe this issue is a duplicate of #169.

**Comment by hrishibhat** [comment]
Escalation rejected

Duplicate of #169 
This issue is a duplicate of #169
